/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class collection_JNICollection */

#ifndef _Included_collection_JNICollection
#define _Included_collection_JNICollection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     collection_JNICollection
 * Method:    allocate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_collection_JNICollection_allocate
  (JNIEnv *, jobject, jint);

/*
 * Class:     collection_JNICollection
 * Method:    enlarge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_collection_JNICollection_enlarge
  (JNIEnv *, jobject);

/*
 * Class:     collection_JNICollection
 * Method:    free
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_collection_JNICollection_free
  (JNIEnv *, jobject);

/*
 * Class:     collection_JNICollection
 * Method:    get
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_collection_JNICollection_get
  (JNIEnv *, jobject, jint);

/*
 * Class:     collection_JNICollection
 * Method:    set
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_collection_JNICollection_set
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     collection_JNICollection
 * Method:    remove
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_collection_JNICollection_remove
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
